### ISSUE TITLE
Glulxercise cannot be compiled with upstream Inform6

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glk-dev#17]
Glulxercise can no longer be compiled with the upstream Inform6 compiler from DavidKinder/Inform6 because it uses hasundo and discardundo, which Inform6 doesn't know about yet.

Can those opcodes be manually encoded?

**Comment by erkyrath** [comment]
Oh, wow. I forgot that that test went into the main line of glulxercise.inf.

The status of hasundo/discardundo is that I implemented them in glulxe/quixe, but that code never made it into the release branch. I think I wanted to implement them in other interpreters like git before I declared it "done". But I never got around to that.

(I've brought the discardundo branches in the glulxe/quixe repos up to date with master.)

Since neither the compiler and interpreter code has ever been released, it feels weird to have the test in glulxercise. So I'm just going to comment it out for now. But maybe this should all be revisited soon.

**Comment by erkyrath** [comment]
For context, the rationale for hasundo/discardundo was to tidy up the Inform parser loop by doing a @saveundo *before* line input, rather than the current awkward sequence of "line input, check for UNDO command, @saveundo, maybe short-circuit back to top".

This is clearly not going to make it into the next major Inform update. But I guess that's a sign that we should get the support into place, so that it can be considered for the next major update after that.

**Comment by erkyrath** [comment]
Commented test out.

**Comment by curiousdannii** [comment]
Thanks!
